---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: versions-data
  labels:
    name: versions-data
spec:
  capacity:
    storage: 10Mi
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - vers=4.2
  nfs:
    path: /srv/versions
    server: 172.22.13.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: versions-data
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: standard
  resources:
    requests:
      storage: 10Mi
  selector:
    matchLabels:
      name: versions-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: versions-json
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      service: versions-json
  replicas: 2
  template:
    metadata:
      labels:
        service: versions-json
    spec:
      containers:
        - name: versions-json
          image: docker.io/philippgille/serve
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /srv
              readOnly: true
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: versions-data
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - op01.kos.kjnet.xyz
                      - op02.kos.kjnet.xyz
                      - op03.kos.kjnet.xyz
                      - op04.kos.kjnet.xyz
                      - op05.kos.kjnet.xyz
                      - op06.kos.kjnet.xyz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: versions-web
spec:
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      service: versions-web
  replicas: 2
  template:
    metadata:
      labels:
        service: versions-web
    spec:
      containers:
        - name: versions-web
          image: quay.io/mizdebsk/versions-web:latest
          env:
            - name: VERSIONS_JSON_URL
              value: http://versions-json:8080/versions.json
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 500m
              memory: 128Mi
            limits:
              cpu: 2000m
              memory: 512Mi
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - op01.kos.kjnet.xyz
                      - op02.kos.kjnet.xyz
                      - op03.kos.kjnet.xyz
                      - op04.kos.kjnet.xyz
                      - op05.kos.kjnet.xyz
                      - op06.kos.kjnet.xyz
---
apiVersion: v1
kind: Service
metadata:
  name: versions-json
  labels:
    service: versions-json
spec:
  ports:
  - port: 8080
  selector:
    service: versions-json
---
apiVersion: v1
kind: Service
metadata:
  name: versions-web
  labels:
    service: versions-web
spec:
  ports:
  - port: 8080
  selector:
    service: versions-web
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: versions
spec:
  rules:
  - host: versions.kos.kjnet.xyz
    http:
      paths:
      - path: /versions.json
        pathType: Prefix
        backend:
          service:
            name: versions-json
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: versions-web
            port:
              number: 8080
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: versions-backend
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: versions-backend
              image: quay.io/mizdebsk/versions-backend:latest
              env:
                - name: OUT_JSON
                  value: /srv/versions.json
                - name: URL_PACKAGE_NAMES
                  value: https://mizdebsk.fedorapeople.org/subject.xml
              volumeMounts:
                - name: data
                  mountPath: /srv
              resources:
                requests:
                  cpu: 100m
                  memory: 128Mi
                limits:
                  cpu: 1000m
                  memory: 512Mi
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: versions-data
          affinity:
            nodeAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  preference:
                    matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - op01.kos.kjnet.xyz
                          - op02.kos.kjnet.xyz
                          - op03.kos.kjnet.xyz
                          - op04.kos.kjnet.xyz
                          - op05.kos.kjnet.xyz
                          - op06.kos.kjnet.xyz
